apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pdfsigner-ingress
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: pdfsigner
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: signer
    ports:
    - protocol: TCP
      port: 8090
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 8091
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mailer-ingress
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: mailer
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: signer
    ports:
    - protocol: TCP
      port: 8083
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 9100
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-ingress
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: uploader
    - podSelector:
        matchLabels:
          app: downloader
    - podSelector:
        matchLabels:
          app: signer
    - podSelector:
        matchLabels:
          app: redis-exporter
    ports:
    - protocol: TCP
      port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-ingress
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: signer
    - podSelector:
        matchLabels:
          app: downloader
    - podSelector:
        matchLabels:
          app: postgres-exporter
    ports:
    - protocol: TCP
      port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq-ingress
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: rabbitmq
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: uploader
    - podSelector:
        matchLabels:
          app: signer
    ports:
    - protocol: TCP
      port: 5672
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 15692
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio-ingress
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: minio
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: uploader
    - podSelector:
        matchLabels:
          app: downloader
    - podSelector:
        matchLabels:
          app: signer
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 9000
  - from:
    - podSelector:
        matchLabels:
          job-name: minio-init
    ports:
    - protocol: TCP
      port: 9000
